#version 450 core

// Local group size
layout(local_size_x = 256) in;

struct Particle {
    vec4 position;
    vec4 velocity_delay;
    ivec4 flags;
};

layout(std430, binding = 4) buffer ParticleBuffer {
    Particle particles[];
};

// Cloud mask used sky camera, so we need the sky camera matrix
layout(std140, binding = 0) uniform CameraBuffer {
    mat4 projection;
    mat4 projection_inv;
    mat4 view;
    mat4 view_inv;
    mat3 view_it;
    vec3 eye_position;
} camera;

layout(binding = 0) uniform sampler2D cloud_mask_texture;
layout(binding = 1) uniform sampler2D surface_mask_texture;
layout(binding = 2) uniform sampler2D sky_depth_texture;

uniform int particle_count;
uniform float delta_time;
uniform int frame_index;
uniform vec3 cloud_world_position;
uniform float cloud_size;
uniform vec3 gravity;
uniform float reset_y;
uniform float spawn_height_range;
uniform float initial_fall_speed;
uniform float max_delay;
uniform float kill_y;
uniform float collision_bias;
uniform float collision_offset;
uniform float restitution;
uniform float stop_speed;

// Used AI to create this random number generator
uint hash_uint(uint x) {
    x ^= x >> 16;
    x *= 2246822519u;
    x ^= x >> 13;
    x *= 3266489917u;
    x ^= x >> 16;
    return x;
}

// Random number generator (no rand in GLSL)
float random01(uint seed){
    return float(hash_uint(seed)) / 4294967295.0;
}

// Convert world space position to UV coord into cloud mask texture (sky space)
vec3 world_to_sky_position(vec3 position_ws)
{
	vec4 sky_position = camera.projection * camera.view * vec4(position_ws, 1.0);
    // perspective divide
	sky_position.xyz /= sky_position.w;
	return sky_position.xyz * 0.5 + 0.5;
}

bool uv_inside_texture(vec2 uv){
    return uv.x >= 0.0 && uv.x <= 1.0 && uv.y >= 0.0 && uv.y <= 1.0;
}

vec3 reconstruct_world_position(vec2 uv, float depth)
{
	vec4 position_cs = vec4(uv * 2.0 - 1.0, depth * 2.0 - 1.0, 1.0);
	vec4 position_vs = camera.projection_inv * position_cs;
	position_vs /= position_vs.w;
	vec4 position_ws = camera.view_inv * position_vs;
	return position_ws.xyz;
}

// Estimate surface normal from depth texture neighboors
vec3 reconstruct_surface_normal(vec2 uv)
{
	vec2 texel_size = 1.0 / vec2(textureSize(sky_depth_texture, 0));

	float d = texture(sky_depth_texture, uv).r;
	float dx_depth = texture(sky_depth_texture, clamp(uv + vec2(texel_size.x, 0.0), vec2(0.0), vec2(1.0))).r;
	float dy_depth = texture(sky_depth_texture, clamp(uv + vec2(0.0, texel_size.y), vec2(0.0), vec2(1.0))).r;

	if (d >= 0.999) {
		return vec3(0.0, 1.0, 0.0);
	}

	vec3 p = reconstruct_world_position(uv, d);
	vec3 px = reconstruct_world_position(clamp(uv + vec2(texel_size.x, 0.0), vec2(0.0), vec2(1.0)), dx_depth);
	vec3 py = reconstruct_world_position(clamp(uv + vec2(0.0, texel_size.y), vec2(0.0), vec2(1.0)), dy_depth);

	vec3 dx = px - p;
	vec3 dy = py - p;
	vec3 normal = cross(dx, dy);

	if (length(normal) < 0.0001) {
		return vec3(0.0, 1.0, 0.0);
	}

	normal = normalize(normal);

    // Point upwards
	if (normal.y < 0.0) {
		normal = -normal;
	}

	return normal;
}

void reset_particle(inout Particle particle, uint seed){
    particle.flags = ivec4(0, 0, 0, 0);
    particle.velocity_delay = vec4(0.0, 0.0, 0.0, random01(seed) * max_delay);
}

// Generate candidate position around the cloud (square)
void prepare_unreleased_particle(inout Particle particle, uint seed) {
    float x = (random01(seed + 1u) - 0.5) * cloud_size;
    float y = (random01(seed + 2u) - 0.5) * spawn_height_range;
    float z = (random01(seed + 3u) - 0.5) * cloud_size;

    vec3 position = cloud_world_position + vec3(x, y, z);

    float vx = (random01(seed + 4u) - 0.5) * 0.4;
    float vz = (random01(seed + 5u) - 0.5) * 0.4;

    particle.position = vec4(position, 1.0);
    particle.velocity_delay.xyz = vec3(vx, -initial_fall_speed, vz);
}

// Constant acceleration motion
void update_released_particle(inout Particle particle) {
    vec3 position = particle.position.xyz;
    vec3 velocity = particle.velocity_delay.xyz;

    position += velocity * delta_time + 0.5 * gravity * delta_time * delta_time;
    velocity += gravity * delta_time;

    particle.position = vec4(position, 1.0);
    particle.velocity_delay.xyz = velocity;
}

void mark_stopped_particle(inout Particle particle, vec2 sky_uv) {
    float surface_value = texture(surface_mask_texture, sky_uv).r;

    if (surface_value > 0.75){
        particle.flags = ivec4(0, 1, 1, 0);
    }
    else {
        particle.flags = ivec4(1, 0, 1, 0);
    }

    particle.velocity_delay.xyz = vec3(0.0);
}

void handle_collision(inout Particle particle) {
    vec3 sky_position = world_to_sky_position(particle.position.xyz);
    vec2 sky_uv = sky_position.xy;

    if (!uv_inside_texture(sky_uv)) {
        return;
    }

    float scene_depth = texture(sky_depth_texture, sky_uv).r;

    if (scene_depth >= 0.999) {
        return;
    }

    float particle_depth = sky_position.z;

    if (particle_depth >= scene_depth - collision_bias) {
        vec3 normal = reconstruct_surface_normal(sky_uv);
        vec3 surface_position = reconstruct_world_position(sky_uv, scene_depth);
        vec3 velocity = particle.velocity_delay.xyz;

        // Bounce
        velocity = reflect(velocity, normal) * restitution; // Loss of energy

        particle.position = vec4(surface_position + normal * collision_offset, 1.0);
        particle.velocity_delay.xyz = velocity;

        // Stop particle
        if (length(velocity) < stop_speed) {
            mark_stopped_particle(particle, sky_uv);
        }
    }
}

void main() {
    // 1. Get particle
    // Current parallel thread index
    uint id = gl_GlobalInvocationID.x;
    if (int(id) >= particle_count) { // not always div by 256
        return;
    }

    Particle particle = particles[id];

    // 2. Upate particle
    uint seed = id * 747796405u + uint(frame_index) * 2891336453u;

    particle.velocity_delay.w -= delta_time;

    // If the particle is unreleased
    if (particle.flags.z == 0) {
        // Try to release
        prepare_unreleased_particle(particle, seed);

        // Check if the particle is inside the cloud
        vec2 sky_uv = world_to_sky_position(particle.position.xyz).xy;
        float mask_value = 0.0;
        if (uv_inside_texture(sky_uv)) {
            mask_value = texture(cloud_mask_texture, sky_uv).r;
        }

        // Check if delay is over
        if (particle.velocity_delay.w <= 0.0 && mask_value > 0.5) {
            // Particule is released
            particle.flags.z = 1;
        }
    }
    // If the particle is released
    else {
        // Update particle position falling
        update_released_particle(particle);
        handle_collision(particle);

        // Check if the particle is on the ground
        if (particle.position.y < reset_y) {
            // Recycle it
            reset_particle(particle, seed + 29u);
        }
    }
    // Avoid projection jitter : translation applies (homogeneous coord)
    particle.position.w = 1.0;

    // 3. Store particle
    particles[id] = particle;
}
